### ISSUE TITLE
Need Couchbase server 2.2.0 (Debian 8)

### ISSUE THREAD

**Issue by pskanawat** [membase/manifest#6]
Hi,
Can @ceejatec / anyone refer me to download links for couchbase server 2.2.0( Debian 8 )?

I couldn't find the couchbase server 2.2.0 for Debian 8 here https://www.couchbase.com/downloads under previous versions.

**Comment by ceejatec** [comment]
Couchbase Server 2.2.0 has been EOL for nearly four years (since 4.0.0 was shipped in October 2015). Debian 8 was released in April 2015 and neither Server 2.x nor 3.x was ever supported there. The first version of Server to support Debian 8 was 4.5.0.

I strongly advise upgrading to a newer and supported version of Server.

**Comment by pskanawat** [comment]
Thanks for the update @ceejatec
